import { Inter } from "next/font/google";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Main from "../components/Main";
import About from "../components/About";
import Skills from "../components/Skills";
import Contact from "../components/Contact";
import { Raleway } from "next/font/google";

const raleway = Raleway({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="scroll-smooth">
      <div className={raleway.className}>
        <Head>
          <title> Akshay ] | Java Developer</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/blacklogo.jpg" />
        </Head>
        <Navbar />
        <Main />
        <About />
        <Skills />
        <Contact />
      </div>
    </div>
  );
}
